'use client';

import React from 'react';

const PrivacyPolicy = () => {
    return (
        <section className="spacing-secton sm:py-14 text-gray-800">
            <h1 className="text-5xl font-semibold mb-4">Privacy Policy</h1>
            <p className="text-lg leading-relaxed sm:mt-10">
                This Privacy Policy outlines our practices regarding the collection, use, and disclosure of your
                information when you engage with our Service. It also explains your privacy rights and the legal
                protections afforded to you.
            </p>

            <section>
                <h2 className="text-4xl font-semibold mt-16">Interpretation and Definitions</h2>
                <p className="text-lg leading-relaxed mt-6">
                    Terms beginning with the capital letters hold specific meanings as defined under the following
                    conditions. The ensuing definitions maintain their significance whether in singular or plural.
                </p>

                <h2 className="text-3xl font-semibold mt-10">For the purposes of the privacy policy</h2>
                <p className="text-lg leading-relaxed mt-6">
                    “Account” means a unique account created for You to access our Service or parts of our Service.
                    <br /><br />
                    “Company” (referred to as either “the Company”, “We”, “Us”, or “Our” in this agreement) refers to
                    Kavelogics Technologies., a Pakistan based software house with its principal place of business at 56 F2,
                    street 7, Block F, PCHS, Lahore, Punjab, Pakistan, 54792.
                    <br /><br />
                    “Personal Data” is any information that relates to an identified or identifiable individual.
                    <br /><br />
                    “Service” refers to the website provider means any natural or legal person who processes the data on
                    behalf of the company. It refers to third-party companies or individuals employed by the company to
                    facilitate the Service, to provide the Service on behalf of the Company, to perform services related to
                    the Service, or to assist the Company in analyzing how the Service is used.
                    <br /><br />
                    “Third-Party Social Media Service” refers to any website or any social network website through which a
                    User can log in or create an account to use the Service.
                    <br /><br />
                    “Usage Data” refers to data collected automatically, either generated by the use of the Service or from
                    the Service infrastructure itself (for example, the duration of page visits).
                    <br /><br />
                    “Website” refers to Kavelogics, accessible from
                    <span className="text-[#00D280]">www.Kavelogics.com</span>
                    <br /><br />
                    “You” means the individual accessing or using the Service, the company, or other legal entity on behalf
                    of which such individual is accessing or using the Service, as applicable.
                </p>
            </section>

            <section className="mt-10">
                <h1 className="text-4xl font-semibold mt-10">Utilization of Your Personal Data</h1>
                <p className="mt-8 text-lg">Kavelogics may use your personal data for the following purposes:</p>

                <h2 className="text-3xl font-semibold mt-10">1. Contractual Obligations</h2>
                <p className="mt-8 text-lg">
                    To facilitate the development, fulfillment, and management of purchase contracts for products,
                    services, or items you have acquired through our platform, or any other contractual agreements you have
                    entered into with us.
                </p>

                <h2 className="text-3xl font-semibold mt-10">2. Communication</h2>
                <p className="mt-8 text-lg">
                    We may reach out to you via email, phone calls, SMS, or other electronic means such as push
                    notifications on our mobile application, to provide updates, essential information regarding our
                    products/services, including security updates, and to offer news, special deals, and general
                    information about offerings similar to those you have previously shown interest in, unless you have opted
                    out.
                </p>

                <h2 className="text-3xl font-semibold mt-10">3. Request Management</h2>
                <p className="mt-8 text-lg">
                    Handling and addressing any inquiries or requests you submit to us.
                </p>

                <h2 className="text-3xl font-semibold mt-10">4. Miscellaneous Purposes</h2>
                <p className="mt-8 text-lg">
                    Your information may also be utilized for activities like data analysis, identifying usage patterns,
                    evaluating the effectiveness of marketing campaigns, and enhancing our services, products, marketing
                    strategies, and overall user experience.
                </p>
            </section>

            <section className="mt-10">
                <h1 className="text-3xl font-semibold mt-10">We may share your personal information under the following circumstances:
                </h1>
                <h1 className="text-4xl font-semibold mt-10">1. Business transitions:
                </h1>
                <p className="mt-8 text-lg">During negotiations or in connection with any merger, sale of assets, financing, or acquisition involving Kavelogics.</p>

                <h2 className="text-3xl font-semibold mt-10">1. Contractual Obligations</h2>
                <p className="mt-8 text-lg">
                    Sharing information with our business partners to provide you with specific products, services, or promotions.
                </p>

                <h2 className="text-3xl font-semibold mt-10">2. UserInterction </h2>
                <p className="mt-8 text-lg">
                    Information shared in public areas or interactions with other users may be visible to all users and possibly distributed publicly. Similarly, interactions through third-party social media services may result in your information being visible to contacts on those platforms.
                </p>

                <h2 className="text-3xl font-semibold mt-10">3. Request Management</h2>
                <p className="mt-8 text-lg">
                    Handling and addressing any inquiries or requests you submit to us.
                </p>

                <h2 className="text-3xl font-semibold mt-10">4. Miscellaneous Purposes</h2>
                <p className="mt-8 text-lg">
                    Your information may also be utilized for activities like data analysis, identifying usage patterns,
                    evaluating the effectiveness of marketing campaigns, and enhancing our services, products, marketing
                    strategies, and overall user experience.
                </p>
            </section>


            <section>
                <h1 className="text-4xl font-semibold mt-10">Retention of Your Personal Data</h1>
                <p className="mt-6 text-lg leading-relaxed">
                    Kavelogics will retain your personal data only for as long as necessary for the purposes outlined in this Privacy Policy. We will keep and utilize your personal data to the extent required to meet our legal obligations, such as complying with applicable laws, resolving disputes, and enforcing our legal agreements and policies.
                    <br /><br />
                    Additionally, Kavelogics will retain usage data for internal analysis purposes. Usage data is typically kept for a shorter duration, except when its utilized to enhance security, improve service functionality, or when legally required to retain it for longer periods.
                </p>

                <h1 className="text-4xl font-semibold mt-14">Transfer of Your Personal Data</h1>
                <p className="mt-6 text-lg leading-relaxed">
                    Kavelogics will retain your personal data only for as long as necessary for the purposes outlined in this Privacy Policy. We will keep and utilize your personal data to the extent required to meet our legal obligations, such as complying with applicable laws, resolving disputes, and enforcing our legal agreements and policies.
                    <br /><br />
                    Additionally, Kavelogics will retain usage data for internal analysis purposes. Usage data is typically kept for a shorter duration, except when its utilized to enhance security, improve service functionality, or when legally required to retain it for longer periods.
                </p>
            </section>

            <section className="mt-10">
                <h1 className="text-2xl font-bold mt-6">Retention of Your Personal Data</h1>
                <p className="text-lg leading-relaxed mt-6">
                    We retain your data only as long as necessary for legal, operational, and analytical purposes.
                    Usage data may be stored for a shorter duration unless required for improvements or security.
                </p>
            </section>

            <section className="mb-10">
                <h1 className="text-2xl font-bold my-6">Transfer of Your Personal Data</h1>
                <p className="text-lg leading-relaxed">
                    Your data may be processed outside of your jurisdiction. By using our service, you consent to such
                    transfers. We take necessary steps to ensure your data is treated securely and per this Privacy Policy.
                </p>
            </section>

            <section className="mb-10">
                <h1 className="text-4xl font-bold mb-6">Disclosure of Your Personal Data</h1>

                <h2 className="text-2xl font-semibold mb-6">Business Transactions</h2>
                <p className="mb-4 text-lg leading-relaxed">
                    Your data may be transferred if Kavelogics is involved in mergers, acquisitions, or sales.
                </p>

                <h2 className="text-2xl font-semibold mb-4">Law Enforcement</h2>
                <p className="mb-4 text-lg leading-relaxed">
                    We may disclose your data to comply with legal obligations or lawful requests by public authorities.
                </p>

                <p className="mb-4 text-lg leading-relaxed">Disclosure may be necessary to:</p>
                <ul className="text-lg leading-relaxed list-decimal ml-6 space-y-2">
                    <li>Comply with legal obligations</li>
                    <li>Protect Kavelogics rights or property</li>
                    <li>Investigate potential wrongdoing</li>
                    <li>Protect user or public safety</li>
                    <li>Defend against legal liabilities</li>
                </ul>

                <p className="mt-4 text-lg leading-relaxed">
                    While we use commercially acceptable methods to protect your data, no method is 100% secure. We cannot
                    guarantee absolute security.
                </p>
            </section>

            <section>
                <h1 className="text-4xl font-semibold mt-10">Childrens Privacy</h1>
                <p className="mt-6 text-lg leading-relaxed">
                    Our Service does not cater to individuals under the age of 13. We do not knowingly gather personally
                    identifiable information from anyone under the age of 13. If you are a parent or guardian and you are
                    aware that your child has provided us with Personal Data, please reach out to us. If we discover that
                    we have collected Personal Data from anyone under the age of 13 without parental consent verification,
                    we will take necessary steps to remove that information from our servers.
                    <br /><br />
                    If we need to rely on consent as a legal basis for processing your information and your country
                    mandates consent from a parent, we may require parental consent before collecting and utilizing that
                    information.
                </p>

                <h1 className="text-4xl font-semibold mt-14">Changes to this Privacy Policy</h1>
                <p className="mt-6 text-lg leading-relaxed">
                    Periodically, we may update our Privacy Policy. We advise you to regularly review this Privacy Policy
                    for any changes. Changes to this Privacy Policy are effective when they are published on this page.
                </p>
            </section>

            <section>
                <h1 className="text-4xl font-bold mt-10">Contact Us</h1>
                <p className="mt-4 text-lg leading-relaxed">
                    If you have questions about this Privacy Policy, you may contact us:
                </p>
                <ul className="leading-relaxed text-lg space-y-1 mt-4 list-none">
                    <li className="mt-6">
                        By email
                        <a href="mailto:info@kavelogics.com" className="text-[#00D280] ml-2" >info@kavelogics.com</a>
                    </li>
                    <li className="mt-6">
                        By visiting
                        <a href="https://www.kavelogics.com" className="text-[#00D280] underline ml-2">this</a> on our website.
                    </li>
                </ul>
            </section>
        </section>

    );
};

export default PrivacyPolicy;
